apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2020-11-27T13:19:05Z"
  generation: 5
  labels:
    app: black-friday
  name: black-friday
  namespace: prod
  resourceVersion: "279274964"
  selfLink: /apis/apps/v1/namespaces/prod/deployments/black-friday
  uid: b4e0a1de-a4ff-4834-aa6d-dc53f2a0bc5d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: black-friday
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: black-friday
    spec:
      containers:
      - image: gcr.io/appointy-prod/black-friday:v6
        imagePullPolicy: IfNotPresent
        name: black-friday
        ports:
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: black-friday
          subPath: default.conf
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
      - command:
        - /app/main
        - -cert=/etc/secrets/tls.crt
        - -key=/etc/secrets/tls.key
        - -upstream=black-friday:8443
        image: gcr.io/appointy-prod/wrp:1
        imagePullPolicy: IfNotPresent
        name: wpreverseproxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: covid19-cm-wrp
        name: black-friday
      - name: secrets
        secret:
          defaultMode: 420
          secretName: ssl-cert-72020
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-27T13:19:05Z"
    lastUpdateTime: "2020-11-30T14:35:50Z"
    message: ReplicaSet "black-friday-664bb957d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-01-16T12:22:44Z"
    lastUpdateTime: "2021-01-16T12:22:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
